#!/usr/bin/env ansible-playbook 
---
# If you like to play: ./ansible/create.yml --skip-tags public_dns,letsencrypt
- hosts: localhost
  connection: local
  become: true
  # gather_facts true because we need the public ip address
  gather_facts: true
  vars_files:
  - ../cluster.yml
  - ../vault.yml
  environment:
    IPA_HOST: "{{ ipa_host }}"
    IPA_USER: "{{ idm_admin_user }}"
    IPA_PASS: "{{ idm_admin_pwd }}"

  tasks:
  - name: Deploy cluster
    import_role: 
      name: openshift-4-cluster
      tasks_from: create-master.yml
